apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: job-name
spec:
  project: default
  source:
    repoURL: https://github.com/CTingy/argocd-exp
    targetRevision: HEAD
    path: staging
    kustomize:
      version: v3.5.4

  destination:
    server: https://kubernetes.default.svc
    namespace: default


# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: my-job
# spec:
#   destination:
#     name: ''
#     namespace: default
#     server: 'https://kubernetes.default.svc'
#   source:
#     path: staging
#     repoURL: 'https://github.com/CTingy/argocd-exp'
#     targetRevision: HEAD
#     kustomize:
#       version: v3.5.4
#   project: default
