apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd  # local apply argo should put this
  name: my-application
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CTingy/argocd-exp
    path: staging
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
