apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-label
  name: my-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-label
  type: ClusterIP
